### ISSUE TITLE
Fail better when Redis isn't installed

### ISSUE THREAD

**Issue by pdehaan** [mozilla/something-awesome#55]
I don't have Redis installed locally, but when I type `npm start` things go a bit silly.
Not sure if we should fail hard[er] if the Redis connection fails.

```sh
➜  something-awesome git:(master) npm start

> portal-alpha@1.0.0 start /Users/pdehaan/dev/github/mozilla/something-awesome
> watchify frontend/src/main.js -o public/bundle.js -d | node server/portal_server.js

Portal app listening on port 3000!

{ Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379 }

{ Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379 }

...
```

**Comment by abhinadduri** [comment]
Addressed in integration_tests branch.
